config/routes.rb
Rails.application.routes.draw do
  root to: 'scooters#index'
  resources :scooters do
    resources :bookings, only: [:create, :new, :index]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [:index, :show]
  devise_for :users

  get 'owned_scooters', to: 'scooters#owned', as: :owned_scooters
  # get 'owned_scooters', to: 'scooters#owned', as: :owned_scooters
  get 'earnings', to: 'bookings#earnings', as: :earnings
   # , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :renter, class_name: "User"
  belongs_to :scooter
  has_one :owner, through: :scooter

  # validates :start_date, presence: true
  # validates :end_date, presence: true
  # validate :end_date_cannot_be_before_start_date
  # validate :start_date_cannot_be_in_the_past
  # validates :booking_price, presence: true

  # def start_date_cannot_be_in_the_past
  #   if !start_date.nil? && start_date < Date.today
  #     errors.add(:start_date, "can't be in the past")
  #   end
  # end

  # def end_date_cannot_be_before_start_date
  #   if !start_date.nil? && !end_date.nil? && end_date < start_date
  #     errors.add(:end_date, "can't be before the start date")
  #   end
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
 before_action :set_booking, only: [:show]
 before_action :set_scooter, only: [:new, :create]

 def index
    # @bookings = Booking.all
    @bookings = policy_scope(Booking).order(start_date: :desc)
    @scooters = current_user.scooters
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.renter = current_user
    @booking.scooter = @scooter
    authorize @booking

    if @booking.save
      redirect_to @booking, notice: 'Booking successfully completed.'
    else
      render :new
    end
  end

  def show
   @marker = [{
    lat: @booking.scooter.latitude,
    lng: @booking.scooter.longitude,
    image_url: helpers.asset_url('scooter1.png')
  }]
end

def owned
  @bookings = current_user.bookings
  authorize @bookings
end

def earnings
 @bookings = policy_scope(Booking).order(start_date: :desc)
 @scooters = current_user.scooters
end

private

    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
      authorize @booking
    end

    def set_scooter
      @scooter = Scooter.find(params[:scooter_id])
    end


    def booking_params
      params.require(:booking).permit(:renter_id, :scooter_id, :start_date, :end_date, :booking_price, :comment)
    end
  end

app/views/bookings/_form.html.erb
<div class="row justify-content-center text-center">

  <%= simple_form_for([@scooter, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <h1>Create new booking</h1>
    <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
    <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
    <%= f.input :booking_price, as: :hidden, required: false %>
    <%= f.label :price_per_day %>
    <li class="list-group-item">$<%= @scooter.price_per_day %></li>
    <br>

      <p>Comment</p>
    <div class="input-group">
     <!--  <div class="input-group-prepend">
        <span class="input-group-text">Comment</span>
      </div> -->
      <textarea class="form-control" aria-label="With textarea" placeholder="Awesome scooter. See you next weekend."></textarea>
    </div>
    <br>

    <h2 class="mt-2 mb-4">Total Price:<span id="totalPrice"> </span> </h2>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value = 'Confirm booking', class: "btn btn-warning" %>
  </div>
  <% end %>


</div>

app/views/bookings/earnings.html.erb
<%= link_to scooters_path do %>
<i class="fas fa-chevron-circle-left ml-3 mt-3 exit-button" style="font-size: 48px;"></i>
<% end %>

<div class="container">
  <% if @scooters.empty? %>
  <h3 class="my-3">It looks like you don't have any scooters yet, <%= current_user.first_name%></h3>
  <h3>Do you want to add a new scooter?</h3>

  <div>
    <%= link_to "Add new scooter", new_scooter_path, class:"btn btn-sm btn-outline-secondary" %>
  </div>

  <% else %>

  <h1 class="">Earnings for Scooters I own</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Booking #</th>
        <th scope="col">Scooter</th>
        <th scope="col">Total Price</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Renter</th>
      </tr>
    </thead>

    <tbody>
     <% @bookings.each_with_index do |booking, index| %>
     <tr class="<%= index.even? ? 'bg-light' : '' %>">
      <th scope="row"><%= booking.id %></th>
      <td><%= booking.scooter.brand %> - <%= booking.scooter.model %></td>
      <td>$<%= booking.booking_price %></td>
      <td><%= booking.start_date.strftime("%e %b %Y ")%></td>
      <td><%= booking.end_date.strftime("%e %b %Y ")%></td>
      <td><%= booking.renter.first_name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <% if @bookings.empty? %>
  <h3 class="my-3">It looks like you don't have any bookings yet, <%= current_user.first_name%></h3>
  <h3>Do you want to rent a scooter for your next trip?</h3>

  <div>
    <%= link_to "Find scooter", scooters_path, class:"btn btn-sm btn-outline-secondary" %>
  </div>

  <% else %>
  <div class="text-center">
    <h1>My bookings</h1>

    <div class="bd-example">
      <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="width: 625px; height: 400px; margin: 0 auto">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://res.cloudinary.com/dvligih2x/image/upload/DyvBkx4htiPSmw4GZUNjho5g" class="d-block w-101" alt="..." style="height: 400px">

            <div class="carousel-caption d-none d-md-block">
              <h5>Your previous rides</h5>
              <p>Enjoy the memories!</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="https://res.cloudinary.com/dvligih2x/image/upload/uEK4qLJ95TmMBrLCUap2DEwK" class="d-block w-100" alt="..." style="height: 400px">
            <div class="carousel-caption d-none d-md-block">
              <h5>Honda XR250</h5>
              <p>Single-cylinder, SOHC, 4-valve, oil-cooled, four-stroke</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="https://res.cloudinary.com/dvligih2x/image/upload/RzUnR6ZdBdxWnwWCYQ43CTwa" class="d-block w-100" alt="..." style="height:400px">
            <div class="carousel-caption d-none d-md-block">
              <h5>Scootify</h5>
              <p>Your next ride, we hope you have a great time.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div class="card-bookings text-center w-100">
      <div class="" style="width: 60%; display: inline-block">
        <% @bookings.each do |booking| %>
        <div class="card-product booking">

          <div style="background-size: cover; width: 175px;" class="h-100 d-flex align-items-end justify-content-center">
            <%= cl_image_tag booking.scooter.photo.key, class:"img-fluid rounded min-vw-25 w-100 object-fit-cover object-fit-center"%>

            <p style="position: absolute; width: 175px; background-color: white;" class="m-0 bg-light text-center">booking id:<%= booking.id %></p>

          </div>
          <div class="card-product-info scooter">
            <div class="d-flex justify-content-between">
              <div class="ml-4 d-flex flex-column justify-content-between h-100">
                <div>
                  <h1 class="m-0"><%= booking.scooter.brand %></h1>
                  <h2 class="m-0 font-weight-lighter "><%= booking.scooter.model %></h2>
                </div>
                <h1 class="mt-4">$<%= booking.booking_price %></h1>
              </div>
              <div class="mr-5">
                <div>
                  <h2 class="mb-1 p-1 text-center" style="border: 1px solid lightgrey; background-color:
                  <%= booking.start_date < Date.today ? "lightgrey" : "white" %>">
                  <i class="far fa-calendar-check"></i> <%= booking.start_date.strftime("%e- %b") %></h2>

                  <h2 class="mb-1 p-1 text-center" style="border: 1px solid lightgrey; background-color:
                  <%= booking.start_date < Date.today ? "lightgrey" : "white" %>">
                  <i class="far fa-calendar-minus"></i> <%= booking.end_date.strftime("%e- %b")%></h2>
                </div>
                <div class="text-center">
                  <a><%= link_to "Leave review!", new_scooter_review_path(booking.scooter), class:"btn btn-outline-secondary px-4" %></a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>

    </div>
    <!-- container closing div -->
  </div>

app/views/bookings/new.html.erb
<%= link_to scooter_path(@scooter) do %>
<i class="fas fa-chevron-circle-left ml-3 mt-3 exit-button" style="font-size: 48px;"></i>
<% end %>

<div class="container">

  <%= render 'form', scooter: @scooter, booking: @booking %>
</div>

app/views/bookings/show.html.erb
<div class="container justify-content-center">
  <div class="text-center my-4">
    <h1>Your booking is confirmed...</h1>
  </div>
  <div class="card-trip justify-content-center p-1" style="width: 600px; margin: 0 auto;">
    <div class="text-center p-1">
      <%= image_tag "scooter.jpg", class: "avatar-large" %>
      <h2 class="mt-2 mb-2">You are going to scoot on a <%= @booking.scooter.brand %> <%= @booking.scooter.model %></h2>
      <p class="mb-3">Transmission: <%= @booking.scooter.transmission %></p>

      <!-- <img src="https://source.unsplash.com/1600x900/?scooter&${<%=@booking.scooter.brand%><%=@booking.scooter.model%>}" class="img-fluid rounded w-50 height-50px object-fit-cover object-fit-center"> -->
      <div class="row justify-content-center">
        <div class="col-12 col-lg-12">
          <% if @booking.scooter.photo.attached? %>
          <%= cl_image_tag @booking.scooter.photo.key, class:"img-fluid rounded min-vw-25 w-100 object-fit-cover object-fit-center"%>
          <% else %>
          <img src="https://source.unsplash.com/1600x900/?scooter&${<%=@scooter.brand%><%=@scooter.model%>}" class="img-fluid rounded min-vw-25 w-100 object-fit-cover object-fit-center" alt="scooter-img">
          <% end %>
        </div>
      </div>

      <p class="my-4" style="font-size: 16px">From <span class="font-weight-bold"><%= @booking.start_date.strftime('%b %d, %Y') %></span></%> to <span class="font-weight-bold"><%= @booking.end_date.strftime('%b %d, %Y') %></span></%> </p>
      <p class="mt-2 mb-4" style="font-size: 16px">Total Price: <span class="font-weight-bold">$<%= @booking.booking_price %></span></p>
      <p class="mt-3 mb-0" style="text-align: left;">Pick-up your scooter here:</p>

      <div class="row justify-content-center">
        <div class="col-12 col-lg-12">
          <div id="mapbox" class="rounded" style="width: 100%; height: 300px;" data-markers="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          <span class="address-box-grey" style="color: white; position: absolute; bottom: 5px; left: 20px;"><%= @booking.scooter.address %></span>
        </div>
      </div>

      <div class="text-center d-flex justify-content-center">
        <h2 class="mt-5 mb-3">
          <%= link_to 'Book a new trip', scooters_path, class:"btn btn-lg btn-warning btn-block" %>
        </h2>
      </div>
    </div>
  </div>
</div>