config/routes.rb
Rails.application.routes.draw do
  root to: 'scooters#index'
  resources :scooters do
    resources :bookings, only: [:create, :new, :index]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [:index, :show]
  devise_for :users

  get 'owned_scooters', to: 'scooters#owned', as: :owned_scooters
  # get 'owned_scooters', to: 'scooters#owned', as: :owned_scooters
  get 'earnings', to: 'bookings#earnings', as: :earnings
   # , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scooter.rb
class Scooter < ApplicationRecord
  belongs_to :owner, class_name: "User"

  has_many :bookings #, dependent: :destroy
  has_many :reviews

  has_one_attached :photo # we might be willing to change it to many. and check how to define which one to show on prod cards that only allow one photo for the time being.

  validates :brand, presence: true
  validates :model, presence: true
  validates :transmission, presence: true, inclusion: { in: %w(manual automatic)}
  validates :year, presence: true
  validates :price_per_day, presence: true
  validates :address, presence: true
  validates :license_type, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/scooters_controller.rb
class ScootersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_scooter, only: [:show, :edit, :update, :destroy]

  # GET /scooters
  def index
    if params[:destination].present?
      @scooters = policy_scope(Scooter).near(params[:destination],3)
      @destination = params[:destination]
    else
      @scooters = policy_scope(Scooter)
    end
    # @scooters = Scooter.all
    # authorize @scooters
    # @category = params[:category]
    # @scooters2 = @scooters.where(category: @category)
    # @scooters = Scooter.geocoded #returns scooters with coordinates
    @markers = @scooters.map do |scooter|
      {
        lat: scooter.latitude,
        lng: scooter.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { scooter: scooter }),
        image_url: helpers.asset_url('scooter1.png')
      }
    end
  end

  # GET /scooters/1
  def show
    # @scooter = Scooter.find(params[:id])
     # @scooter = Scooter.geocoded #returns scooters with coordinates
     @marker = [{
      lat: @scooter.latitude,
      lng: @scooter.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { scooter: @scooter }),
      image_url: helpers.asset_url('scooter1.png')
    }]
  end

  # GET /scooters/new
  def new
    @scooter = Scooter.new
    authorize @scooter
  end


  # GET /scooters/1/edit
  def edit
  end

  # POST /scooters
  def create
    @scooter = Scooter.new(scooter_params)
    @scooter.owner = current_user
    authorize @scooter

     # raise
     if @scooter.save
      redirect_to @scooter, notice: 'scooter was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /scooters/1
  def update
    if @scooter.update(scooter_params)
      redirect_to @scooter, notice: 'scooter was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /scooters/1
  def destroy
    if @scooter.bookings.count > 0
      redirect_to owned_scooters_url, notice: 'You have dependant bookings that do not allow you to delete your bike.'
    else
      @scooter.destroy

      redirect_to owned_scooters_url, notice: 'scooter was successfully destroyed.'
    end

  end

  def owned
    @scooters = current_user.scooters
    authorize @scooters
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scooter
      @scooter = Scooter.find(params[:id])
      authorize @scooter
    end

    # Only allow a trusted parameter "white list" through.
    def scooter_params
      params.require(:scooter).permit(:brand, :model, :transmission, :year, :price_per_day, :address, :license_type, :photo)
    end

  end

app/views/scooters/_form.html.erb
 <div class="container">
  <div class="row justify-content-center text-center">
    <%= simple_form_for(@scooter) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :brand %>
      <%= f.input :model %>
      <%= f.input :transmission, as: :radio_buttons, collection: %w(manual automatic)  %>
      <%= f.input :year %>
      <%= f.input :price_per_day %>
      <%= f.input :address %>
      <%= f.input :license_type, as: :radio_buttons, collection: %w(A1 A2 A3) %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class:"btn btn-warning" %>
    </div>
    <% end %>

  </div>
</div>
<style>
.string {
  font-weight: bold;
}
.col-form-label {
  font-weight: bold;
}
.integer {
  font-weight: bold;
}

</style>

app/views/scooters/_info_window.html.erb
<h5><%= scooter.brand %> - <%= scooter.model %></h5>
<span>
  <%= cl_image_tag scooter.photo.key, style:"height: 150px; width: 100%; object-fit: cover;", class:"card-img-top :width=>70 :height=>20 :crop=>'scale' z"%>
</span>
<h5 class="mt-3">$ <%= scooter.price_per_day %> / Day</h5>
<p><%= scooter.address %></p>
<h5><%= link_to "Book now", scooter_path(scooter), class: "btn btn-outline-secondary" %></h5>

app/views/scooters/_mapbox.html.erb
<div class="container">
<div id="mapbox" style="width: 100%; height: 800px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/scooters/edit.html.erb
<%= link_to owned_scooters_path do %>
<i class="fas fa-chevron-circle-left ml-3 mt-3 exit-button" style="font-size: 48px;"></i>
<% end %>

<div class="container text-center">
  <h1>Edit Scooter</h1>
</div>

<%= render 'form', scooter: @scooter %>

app/views/scooters/edit.htmnl.erb
<h1>Editing Scooter</h1>

<%= render 'form', scooter: @scooter %>

<%= link_to 'Show', @scooter %> |
<%= link_to 'Back', scooter_path %>

app/views/scooters/index.html.erb
<!-- app/views/scooters/index.html.erb -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1538895490524-0ded232a96d8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60);">
  <div class="container">
    <div class="text-center">
      <h1 class="banner-title">Scootify the town! </h1>
      <p>
        <span id="banner-typed-text"></span>
      </p>

    <form class="form-inline justify-content-center my-5">
      <input id="searchbox" class="form-control mr-sm-2 text-left" type="search" placeholder="Try belgrano" aria-label="Search" name="destination">
      <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
    </form>

    <% if @destination && @scooters.any? %>
        <p class="banner-title">Oki dokiee. Lets Scoot in <em><strong><%= @destination %>!</strong></em> </p>
    <% elsif @destination.present? %>
        <p class="banner-title"> Sorry, we currently have no scooters on the searched location. Scootify coming soon to your area :)</p>
      <% end %>

    </div>
  </div>
</div>

  <%# if @scooters.empty? %>
   <!--  <h4 class="my-2 text-center"> Sorry! We currently have no scooters on the searched location. <br> Coming soon Scootify will land in your area!</h4> -->
  <%# else %>
  <%# end %>
<% if @destination && @scooters.any? %>
  <%flash[:alert] = "We have found #{@scooters.count(:id)} scooters in your searched area! " %>
   <% else %>
<% end %>

<div class="d-block d-lg-flex">

  <div class="cards flex-grow-1">
    <% @scooters.each do |scooter| %>
    <div class="card-wrapper">
      <div class="card rounded scale">
        <%= link_to scooter_path(scooter) do %>
          <% if scooter.photo.attached? %>
             <%= cl_image_tag scooter.photo.key, style:"height: 180px; width: 320px; object-fit: cover;", class:"card-img-top :width=>70 :height=>20 :crop=>'scale'"%>
          <% else %>
            <img src="https://source.unsplash.com/1600x900/?scooter&${<%=scooter.brand%><%=scooter.model%>}"class="card-img-top" alt="scooter-img" style="height: 180px; width: 320px; object-fit: cover;">
          <% end %>
        <% end %>
        <div class="card-body d-flex align-items-top justify-content-between my-0 p-3">
          <div class="card-text">
            <h5 class="card-title m-0"><%= scooter.brand %> <%= scooter.model %></h5>
            <p class="card-text" style="color: grey;">
              <i class="fas fa-<%= scooter.transmission == 'automatic' ? 'sync-alt' : 'cog' %>"></i> <%= scooter.transmission %></p>
          </div>
          <div class="d-flex flex-column align-items-center">
            <div class="price">
              <p class="m-0 price-box-green px-2 py-0">$<%= scooter.price_per_day %> / D</p>
            </div>
            <div class="ratings-method mt-1" style="font-size: 14px;">
              <% ratings = [] %>
              <% scooter.reviews.each do |review| %>
              <% ratings << review.rating %>
              <% end %>
              <span><i class="fas fa-star text-warning"></i> <%= average = (ratings.sum / ratings.size.to_f).round(1) %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
    <% if @scooters.empty? %>
    <% else %>
        <div id="mapbox" style="width: 100%; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <% end %>
  </div>

</div>

app/views/scooters/new.html.erb
<%= link_to scooters_path do %>
<i class="fas fa-chevron-circle-left ml-3 mt-3 exit-button" style="font-size: 48px;"></i>
<% end %>
<div class="container text-center">
  <h1>Add new Scooter</h1>
</div>

<%= render 'form', scooter: @scooter %>

app/views/scooters/owned.html.erb
<%= link_to scooters_path do %>
<i class="fas fa-chevron-circle-left ml-3 mt-3 exit-button" style="font-size: 48px;"></i>
<% end %>

<div class="container">
   <% if @scooters.empty? %>
  <h3 class="my-3">It looks like you don't have any scooters yet, <%= current_user.first_name%></h3>
  <h3>Do you want to add a new scooter?</h3>

  <div>
    <%= link_to "Add new scooter", new_scooter_path, class:"btn btn-sm btn-outline-secondary" %>
  </div>


  <% else %>
  <div class="text-center mb-3">
    <h1>My owned scooters</h1>
  </div>

  <% @scooters.each do |scooter| %>
    <div class="card-product">
         <% if scooter.photo.attached? %>
              <%= cl_image_tag scooter.photo.key, class:"card-img-top :width=>70 :height=>53 :crop=>'scale'"%>
         <% else %>
              <img src="https://source.unsplash.com/1600x900/?scooter&${<%=scooter.brand%><%=scooter.model%>}"class="card-img-top" alt="scooter-img">
         <% end %>
        <div class="card-product-infos d-flex justify-content-between w-100">
        <div>
          <h2><%= scooter.brand %> - <%= scooter.model %></h2>
          <p>transmission: <%= scooter.transmission %></p>
          <p>year: <%= scooter.year %></p>
          <p>$ per day: <%= scooter.price_per_day %></p>
          <p>pick-up address: <%= scooter.address %></p>
          <p>license type: <%= scooter.license_type %></p>
        </div>
        <div>
          <%= link_to "Edit", edit_scooter_path(scooter), class:"btn btn-sm btn-outline-secondary" %>
          <%= link_to 'Delete', scooter_path(scooter), method: :delete, class:"btn btn-sm btn-outline-secondary ml-1 mr-5", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/scooters/show.html.erb
<%#= link_to "Go Back", "/", class: "btn btn-dark ml-2 mt-2" %>
<%= link_to scooters_path do %>
<i class="fas fa-chevron-circle-left ml-3 mt-3 exit-button" style="font-size: 48px;"></i>
<% end %>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <% if @scooter.photo.attached? %>
      <%= cl_image_tag @scooter.photo.key, class:"img-fluid rounded min-vw-25 w-100 object-fit-cover object-fit-center"%>
      <% else %>
      <img src="https://source.unsplash.com/1600x900/?scooter&${<%=@scooter.brand%><%=@scooter.model%>}" class="img-fluid rounded min-vw-25 w-100 object-fit-cover object-fit-center" alt="scooter-img">
      <% end %>
    </div>
  </div>


  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="">
          <h2><%= @scooter.brand %> <%= @scooter.model %></h2>
          <h6><span style="font-style: italic;">
            <i class="fas fa-<%= @scooter.transmission == 'automatic' ? 'sync-alt' : 'cog' %>"></i>
            <%= @scooter.transmission %></span></h6>
        </div>

        <div class="d-flex flex-column align-items-center">
          <p class="m-0 price-box-green"><span class="font-weight-bold">$ <%= @scooter.price_per_day %></span> / day</p>
          <% ratings = [] %>
          <% @scooter.reviews.each do |review| %>
          <% ratings << review.rating %>
          <% end %>
          <span><i class="fas fa-star text-warning mt-3"></i> <%= average = (ratings.sum / ratings.size.to_f).round(1) %> (<%= ratings.size %>)</span>
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">

      <div class="d-flex align-items-center my-3">
        <div class="flex-grow-1" style="height: 2px; background-color: lightgrey;"></div>
        <p class="px-3 m-0" style="background-color: #f4f4f4; color: grey;">
          Information about <%= @scooter.brand %> <%= @scooter.model %>
        </p>
        <div class="flex-grow-1" style="height: 2px; background-color: lightgrey;"></div>
      </div>

      <div class="text-center mb-5">
        <p class="m-0">Year: <span class="font-weight-bold"><%= @scooter.year %></span></%> </p>
        <p class="m-0">Required License: <span class="font-weight-bold"><%= @scooter.license_type %></span></p>
      </div>

      <div class="d-flex align-items-center justify-content-center m-4">
        <img src="https://avatars0.githubusercontent.com/u/30577676?s=460&v=4" class="avatar-large" />
        <div class="ml-3">
          <p class="m-0"><span style="color: grey; font-weight: bold; font-size: 12px;">Your Owner:</span></p>
          <p class="m-0"><span class="font-weight-bold"><%= @scooter.owner.first_name %> <%= @scooter.owner.last_name %></span></%> </p>
        </div>
      </div>

      <div class="flex-grow-1 mt-4" style="height: 2px; background-color: lightgrey;"></div>

      <div class="text-center">
        <a><%= link_to "Book now!", new_scooter_booking_path(@scooter), class:"btn btn-warning px-4 m-4" %></a>
      </div>

    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div id="mapbox" class="rounded" style="width: 100%; height: 300px;" data-markers="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      <span class="address-box-grey" style="color: white; position: absolute; bottom: 5px; left: 20px;"><%= @scooter.address %></span>
    </div>
  </div>
  <br>

  <!-- Reviews for scooter  -->

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h3>Reviews</h3>
      <div class="notification">
        <div class="notification-content">
          <% @scooter.reviews.each do |review| %>
          <div class="my-3 d-flex bg-white">
            <div class="mx-3 py-3 text-center">
              <img src='https://kitt.lewagon.com/placeholder/users/Eschults' class="avatar"/>
              <p class="m-0"><small><%= review.renter.first_name %></small></p>
            </div>
            <div class="d-flex flex-column flex-grow-1 justify-content-around py-3">
              <p class="m-0">
                <% 5.times do |num| %>
                <i class="fa<%=review.rating < num ? 'r' : 's' %> fa-star text-warning"></i>
                <% end %>
              </p>
              <p class="m-0"><%= review.comment %></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- closing div of container -->
</div>